apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus.yaml
  - grafana.yaml
  - alertmanager.yaml

commonLabels:
  app.kubernetes.io/part-of: enclii
  app.kubernetes.io/managed-by: kustomize

# Common annotations
commonAnnotations:
  enclii.dev/component: monitoring
