apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: status-enclii

namespace: enclii

resources:
  - ../base
  - configmap.yaml

# Instance-specific labels
commonLabels:
  app.kubernetes.io/instance: status-enclii

# Patches for Enclii-specific configuration
patches:
  # Update deployment name and selectors
  - patch: |-
      - op: replace
        path: /metadata/name
        value: status-enclii
      - op: replace
        path: /spec/selector/matchLabels/app
        value: status-enclii
      - op: replace
        path: /spec/template/metadata/labels/app
        value: status-enclii
    target:
      kind: Deployment
      name: status

  # Update service name and selector
  - patch: |-
      - op: replace
        path: /metadata/name
        value: status-enclii
      - op: replace
        path: /spec/selector/app
        value: status-enclii
    target:
      kind: Service
      name: status

images:
  - name: ghcr.io/madfam-org/enclii-status
    newName: ghcr.io/madfam-org/enclii/enclii-status
    newTag: cf9e506859feacf51159da11f27bba116d9d9180
