apiVersion: v1
kind: Service
metadata:
  name: verdaccio
  namespace: npm-registry
  labels:
    app.kubernetes.io/name: verdaccio
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4873
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: verdaccio
