apiVersion: v1
kind: Service
metadata:
  name: status
  labels:
    app: status
spec:
  type: ClusterIP
  selector:
    app: status
  ports:
  - name: http
    port: 80
    targetPort: 4204
    protocol: TCP
